### ISSUE TITLE
json preview + bundle explorer

### ISSUE THREAD

**Issue by trostalski** [trostalski/fhir-creator#37]

**Comment by ItIsGreg** [comment]
Started working on branch jsonPreview

**Comment by ItIsGreg** [comment]
Please specify desired bundle explorer functionality/UI

**Comment by ItIsGreg** [comment]
implemented jsonPreview for resources on jsonPreview

**Comment by trostalski** [comment]
json preview is merged

**Comment by trostalski** [comment]
Both features are implemented, closing.
