### ISSUE TITLE
Import Profile not working

### ISSUE THREAD

**Issue by ItIsGreg** [trostalski/fhir-creator#41]
When using the Import Button and selecting Profile and uploading a profile the error message file is not a bundle appears.
When using the Upload Profile button it works.

Expected Behaviour:
the Import Button works for profiles in the same way as the Upload Profile buttons

**Comment by trostalski** [comment]
this is because the wrong function is triggered due to the hidden input elemet

**Comment by trostalski** [comment]
should work on develop branch
